name: Lint and Typecheck
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: bun install --frozen-lockfile
    - name: Lint
      run: bun run lint
    - name: Check types
      run: bun run check
