name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "ossianwallengren.se ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF/R5/TEFX6HMdHUhwB2tdesdvw7pDt4UDHcgem1cyrh" >> ~/.ssh/known_hosts
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Run docker compose up
        run: docker compose up -d --build
        env:
          DOCKER_HOST: "ssh://ossian@ossianwallengren.se"
          DOCKER_BUILDKIT: "0"
